# Generated by Django 3.0.1 on 2019-12-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191224_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='library.jpg', upload_to='', verbose_name='upload_to =author_thumbnails'),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='library.jpg', upload_to='', verbose_name='upload_to =book_thumbnails'),
        ),
    ]
